apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-sample-component
  annotations:
    github.com/project-slug: lshwayne96/backstage-sample-component
spec:
  owner: user1
  type: other
  lifecycle: unknown
