# Site name
site_name: My Sample Project Official Documentation

# Navigation menu
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Install: install.md
  - Configuration: configuration.md
  - Example: example.md
  - Development: development.md
  - Deployment: deployment.md
  - Release notes: release_notes.md
  
# Theme
theme:
    name: mkdocs
    static_templates:
      - 404.html

plugins:
  - techdocs-core
